name: umap_analysis
channels:
  - conda-forge
  - defaults
  - https://conda.anaconda.org/conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - chardet=5.2.0=pyhd8ed1ab_3
  - contourpy=1.3.0=py39h2b77a98_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.59.1=py39h5769e4c_0
  - freetype=2.14.1=h57928b3_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - graphite2=1.3.14=hac47afa_2
  - greenlet=3.2.4=py39hdb6649d_0
  - harfbuzz=11.0.0=h9e37d49_0
  - icu=75.1=he0c23c2_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - kiwisolver=1.4.7=py39h2b77a98_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.18=hf2c6c5f_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libboost=1.86.0=h9dfe17d_5
  - libboost-python=1.86.0=py39h8f1c5a3_3
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.8=default_ha2db4b5_2
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libglib=2.84.0=h7025463_0
  - libgomp=15.2.0=h8ee18e1_16
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libpng=1.6.54=h7351971_0
  - libpq=17.7=h7c87ebf_1
  - librdkit=2025.03.5=h0cb3073_0
  - libsqlite=3.51.2=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - llvmlite=0.43.0=py39he94c479_1
  - matplotlib=3.9.4=py39hcbf5309_0
  - matplotlib-base=3.9.4=py39h5376392_0
  - mkl=2025.3.0=hac47afa_455
  - munkres=1.1.4=pyhd8ed1ab_1
  - numba=0.60.0=py39h5dcb127_0
  - numpy=2.0.2=py39h60232e0_1
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.1=hf411b9b_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.3.1=py39h743b7ac_0
  - pcre2=10.44=h99c9b8b_2
  - pillow=11.3.0=py39hbad85af_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - pthread-stubs=0.4=h0e40799_1002
  - pycairo=1.28.0=py39h2b67685_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyside6=6.9.0=py39h5cc861e_0
  - python=3.9.23=h8c5b53a_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.0=h83cda92_0
  - rdkit=2025.03.5=py39hfb65f61_0
  - reportlab=4.4.1=py39ha55e580_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - scikit-learn=1.6.1=py39hdd013cc_0
  - scipy=1.13.1=py39h1a10956_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlalchemy=2.0.43=py39h0802e32_0
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h6ed50ae_3
  - tornado=6.5.2=py39h0802e32_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=16.0.0=py39ha55e580_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - colorama==0.4.6
      - mapchiral==0.0.7
      - pynndescent==0.6.0
      - tqdm==4.67.1
      - umap-learn==0.5.11
prefix: C:\Users\Admin\anaconda3\envs\umap_analysis
